### ISSUE TITLE
Presenting Popover in UIButton Inside UITableViewCell

### ISSUE THREAD

**Issue by jaytrixz** [corin8823/Popover#10]
How to do this? When I do it, the arrow gets pointed somewhere else.

**Comment by corin8823** [comment]
@jaytrixz I think this article is to your help.
http://stackoverflow.com/questions/2795900/how-can-i-get-the-uitableview-scroll-position-so-i-can-save-it

**Comment by jaytrixz** [comment]
@corin8823 Thanks! Checking it out now.
