### ISSUE TITLE
Popover crashes on iPad

### ISSUE THREAD

**Issue by vaibhav-varshaaweblabs** [corin8823/Popover#104]
Popover crashes on iPad

> *** Terminating app due to uncaught exception 'NSGenericException', reason: 'Your application has presented a UIAlertController of style UIAlertControllerStyleActionSheet. The modalPresentationStyle of a UIAlertController with this style is UIModalPresentationPopover. You must provide location information for this popover through the alert controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem.  If this information is not known when you present the alert controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.'

**Comment by corin8823** [comment]
I think your crash is caused by UIAlertController.  this article is useful for you.
https://stackoverflow.com/questions/31577140/uialertcontroller-is-crashed-ipad
