### ISSUE TITLE
[Request] A new version with the latest code

### ISSUE THREAD

**Issue by mzhangFE** [corin8823/Popover#109]
Hello, 

Thanks for your great work on implementing this library. We are using it in our application. We really like the recently added feature of providing an "auto" type when specifying the preferred popover direction which solves some issues we found. We noticed that the feature is not in the latest release 1.2.0 yet. Could you please do a new release with the latest code base? 

Thanks very much for your help.

**Comment by corin8823** [comment]
I'm sorry I could not react so busily.
But we responded
https://github.com/corin8823/Popover/releases/tag/1.2.1
