### ISSUE TITLE
Type 'CAShapeLayerFillRule' (aka 'NSString') has no member 'evenOdd'

### ISSUE THREAD

**Issue by richschonthal** [corin8823/Popover#115]
I'm getting this compiler error with 1.2.1 on the line:
`fillLayer.fillRule = CAShapeLayerFillRule.evenOdd`

**Comment by richschonthal** [comment]
Never mind, xcode just lost it's mind - I restarted it and the issue went away!

**Comment by AnhNH2512** [comment]
I got similar issue with you. I've restart xcode and my mac, but this issue cannot resolve. When I comment out that line, It's working well.

**Comment by Coder-Ivan** [comment]
`fillLayer.fillRule = kCAFillRuleEvenOdd`
