### ISSUE TITLE
How do I change the starting show location?

### ISSUE THREAD

**Issue by rgmyyw** [corin8823/Popover#138]
How do I fix Popover starting position by depending on the left or right, rather than from the center
如何让 Popover  起始位置固定是依赖左边或者是右边，而不是从中心位置显示

**Comment by rgmyyw** [comment]
![NG](https://tva1.sinaimg.cn/large/007S8ZIlgy1ggifyfa2x3j30u01sxwik.jpg)

![OK](https://tva1.sinaimg.cn/large/007S8ZIlgy1ggifyhwwepj30u01sxgpo.jpg)

**Comment by tallalj** [comment]
You can do the following:
- Adjust the view's frame, which will be shown in the popover
- Adjust the popover type `.type(.up)` or something similar.
