### ISSUE TITLE
Position incorrect

### ISSUE THREAD

**Issue by cwssouza** [corin8823/Popover#15]
Hello, how are you? When running my popover the code is displayed at the top left instead of displaying in the same position of the clicked icon, there's something I can change to correct position?

`@IBAction func cliqueOpcoesCelula(sender: UIButton)
    {          
        let identificador : String = "celulaEvento"
        let celula = self.tableView.dequeueReusableCellWithIdentifier(identificador) as!celulaEventoTableViewCell
        
        //let startPoint = CGPoint(x: self.view.frame.width - 60, y: 100)
        
        let aView = UIView(frame: CGRect(x: 0, y: 0, width: self.view.frame.width, height: 180))
        let popover = Popover()
        popover.show(aView, fromView: celula.eventoTitulo) //popover.show(aView, point: startPoint)
    }`

**Comment by corin8823** [comment]
Hi! I think this answer is useful to you :)
https://github.com/corin8823/Popover/issues/10
