### ISSUE TITLE
How to set options in Objective-C

### ISSUE THREAD

**Issue by rico237** [corin8823/Popover#17]
Im trying to use your library in an Objective-C project but i don't seem to find out how to set options to a popover object ..
Could someone help me ? 
Thank you

**Comment by corin8823** [comment]
Hi @rico237 :)
I was supported in [this PR](https://github.com/corin8823/Popover/pull/18) 
Please try master branch.
Not only options enum but also you can set properties.

**Comment by bhaumikdesai91** [comment]
I tried using this class in Objective C but it doesn't support the init method. So how can I use this in Objective C?

**Comment by rico237** [comment]
@bhaumikdesai91 If you want to use the init method just copy-paste the xib file and launch the file by calling the init with nib name + the name of the xib file you just paste in your project :)

**Comment by rico237** [comment]
@bhaumikdesai91 try to use `Popover* thePopover = [Popover new];`

**Comment by corin8823** [comment]
Hi! @rico237 and @bhaumikdesai91 
I was supported in [this PR](https://github.com/corin8823/Popover/pull/20)
And add objc example for https://github.com/corin8823/Popover/tree/master/ExampleObjc
Please try ExampleObjc and master branch.

**Comment by bhaumikdesai91** [comment]
Thanks for your response @rico237
