### ISSUE TITLE
[Resolved] Inifinite layoutSubviews loop

### ISSUE THREAD

**Issue by jonathan-vinova** [corin8823/Popover#22]
I encountered a weird issue when the popover is not showing, while it totally disabled the screen, turned out there was an infinite layoutSubviews loop.

The solution is simple, just want to share if anybody encounter this issue.

[https://github.com/jonathan-vinova/Popover/commit/61c79b40d036aaa06329d880642d2456439d2339](url)

**Comment by corin8823** [comment]
Hi @jonathan-vinova
Thanks, simple solution :)

**Comment by asifbilal-vteams** [comment]
This issue is still happening in the Cocoa Pods version. Please update that also.

**Comment by corin8823** [comment]
Thank reminder.
Please try to make sure in this version.
https://github.com/corin8823/Popover/releases/tag/0.9.1
