### ISSUE TITLE
App Freezing when using SnapKit to set contraints

### ISSUE THREAD

**Issue by marcelogfsouza** [corin8823/Popover#26]
Hi, I am having an issue while using SnapKit to set the subviews constraints for the Popover. If I set the frame manually, it works fine, if I use SnapKit, it freezes. Maybe is related to the issue  #22 
Thanks. Marcelo

**Comment by corin8823** [comment]
Hi! Thank you for reporting
Please try to make sure in this version.
https://github.com/corin8823/Popover/releases/tag/0.9.1
Please report, when you reproduce this bug

**Comment by marcelogfsouza** [comment]
Hi. I tested it today and it's working perfect. Thanks.
