### ISSUE TITLE
Issue about swift3.0 from cocoapods

### ISSUE THREAD

**Issue by DanielLe232** [corin8823/Popover#43]
Hello guy
Firstly, This is an awesome library popover swift 💯 
I see in requirement, it supports xCode 8+ and swift 3.0 but when I install from pods it has only version 0.9.1.
So if i mistake anywhere, i need advice from you.
thank

**Comment by corin8823** [comment]
Thanks reports!
Please try because I think the move.
https://cocoapods.org/?q=popover

**Comment by DanielLe232** [comment]
it work
Thank.

**Comment by ztwei** [comment]
Versions later than 0.9.1 are marked as pre-release currently, 
I tried below and it worked for me:
`pod 'Popover', :git => 'https://github.com/corin8823/Popover.git', :tag => '1.0.1'`

**Comment by corin8823** [comment]
Thanks reports!
https://github.com/corin8823/Popover/releases/tag/1.0.1
