### ISSUE TITLE
Blur effect ?

### ISSUE THREAD

**Issue by LeonardBonfils** [corin8823/Popover#5]
Hey!

Really helpful library, thanks a lot. How would I go about creating a nice little blur effect on the background view when I'm viewing a popover view ? Kind of like the typical iOS blur effect.

Thanks

**Comment by corin8823** [comment]
Hi!

Thank you for the idea of blur.
I was supported in [this PR](https://github.com/corin8823/Popover/pull/6) .
So please try using :)

**Comment by LeonardBonfils** [comment]
I just added it to my project. Will let you know how well it works.


From: Yusuke Takahashi
Reply-To: corin8823/Popover
Date: Saturday, November 28, 2015 at 9:55 PM
To: corin8823/Popover
Cc: Léonard Bonfils
Subject: Re: [Popover] Blur effect ? (#5)


Hi!

Thank you for the idea of blur.
I was supported in this PR<https://github.com/corin8823/Popover/pull/6> .
So please try using :)

**Comment by corin8823** [comment]
Thanks your great idea! 
I'm glad to know this library is helpful for you.
