### ISSUE TITLE
can't run the project

### ISSUE THREAD

**Issue by CoderYLZhang** [corin8823/Popover#52]
![image](https://cloud.githubusercontent.com/assets/13221319/21841590/c91c96aa-d81d-11e6-949e-6f0948ce0f86.png)

**Comment by corin8823** [comment]
I want you to check if you run `pod install`

```
$ cd Example
$ pod install
```

**Comment by jonauz** [comment]
Same happens to me. Xcode fails after doing install for this pod.
You can close and reopen Xcode, but "Popover" class not recognised, can't find it.

**Comment by corin8823** [comment]
I can't reappear... 
I can run this project
``` 
$ git clone git@github.com:corin8823/Popover.git
$ cd Popover/Example
$ pod --version
1.1.1
$ pod install
$ open Popover.xcworkspace
```

**Comment by corin8823** [comment]
Closing this due to lack of response
