### ISSUE TITLE
How to customize arrow

### ISSUE THREAD

**Issue by marioilianov94** [corin8823/Popover#56]
Hi,
I want to make a custom view with border but I want to make the border with the arrow, now I have this:

![image](https://cloud.githubusercontent.com/assets/9165412/22417904/d820d3f6-e6d6-11e6-8631-3984c9cf989c.png)

But I want to make something like this.

![image](https://cloud.githubusercontent.com/assets/9165412/22418054/8bab7a7a-e6d7-11e6-9b56-0cc9aa9bccce.png)

Can you help me? Thanks :)

**Comment by marioilianov94** [comment]
I need help to do this :)

**Comment by corin8823** [comment]
I'm sorry to be late.
Although it is not impossible, it takes time to display cleanly. I do not have much time..
```
UIColor.red.setStroke()
arrow.lineWidth = 4
arrow.stroke()

color.setFill()
arrow.fill()
```

![2017-02-06 18 09 18](https://cloud.githubusercontent.com/assets/7766840/22640784/726c690a-ec97-11e6-8c6d-69c6501ed004.png)

**Comment by marioilianov94** [comment]
I'll try it, thanks ;)

**Comment by jkritikos** [comment]
Hey @marioilianov94 did you make any progress with this?
