### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by BhaktiKarva** [corin8823/Popover#70]
Helo, I just installed version 1.0.4 because I am using Swift 3.0
I tried to build the project but it gives me error in the Popover.swift file at -  self.showAsDialog(contentView, inView: UIApplication.shared.keyWindow!)
error - 'shared' is unavailable. Use view controller based solutions where appropriate instead.

Please help.

**Comment by BhaktiKarva** [comment]
![1](https://cloud.githubusercontent.com/assets/28924862/26499537/afd232c0-4250-11e7-82f1-b46c362eda34.png)

**Comment by corin8823** [comment]
ummm
Can I call `UIApplication.shared` on your project.
If it can not be called, there is a possibility that it is not swift3.0

**Comment by BhaktiKarva** [comment]
I checked and I cannot call `UIApplication.shared`. Actually I am using this in a custom-keyboard extension and not in the main app. Is that why I am facing this issue?

**Comment by BhaktiKarva** [comment]
How can I change it to use in the keyboard extension. any help would be greatly appreciated.

**Comment by corin8823** [comment]
https://developer.apple.com/library/content/documentation/General/Conceptual/ExtensibilityPG/ExtensionOverview.html#//apple_ref/doc/uid/TP40014214-CH2-SW2

> Access a sharedApplication object, and so cannot use any of the methods on that object

**Comment by corin8823** [comment]
You may be able to build it if you delete the code below
```
  open func showAsDialog(_ contentView: UIView) {
    guard let rootView = UIApplication.shared.windows.last ?? UIApplication.shared.keyWindow else {
        return
    }
    self.showAsDialog(contentView, inView: rootView)
  }

  open func show(_ contentView: UIView, fromView: UIView) {
    guard let rootView = UIApplication.shared.windows.last ?? UIApplication.shared.keyWindow else {
        return
    }
    self.show(contentView, fromView: fromView, inView: rootView)
  }
```

**Comment by BhaktiKarva** [comment]
But will it work as expected?

**Comment by corin8823** [comment]
Internally it gets the key window and just calls the following
`func show(_ contentView: UIView, fromView: UIView, inView: UIView)`

**Comment by BhaktiKarva** [comment]
So i can call this function instead of show(_ contentView: UIView, fromView: UIView) to show the popup?

**Comment by BhaktiKarva** [comment]
It works 👍 Thank you so much :)

**Comment by corin8823** [comment]
very good!  It may correspond in the future for app extension.
