### ISSUE TITLE
UITableView "didSelect Cell Delegate Method Not Fired" 

### ISSUE THREAD

**Issue by Meonardo** [corin8823/Popover#74]
I added the tableView as a custom view to the popTip, when I try to tap the cell on my tableView nothing happened. I think it needs to be turned off the property of  `cancelsTouchesInView`  all **Gestures** you added to the popTip itself and  the containerView.

**Comment by corin8823** [comment]
Please look at [this example](https://github.com/corin8823/Popover/tree/master/Example)

**Comment by corin8823** [comment]
Closing this due to lack of response
