### ISSUE TITLE
1.0.6 seems to break dismiss when touching outside of popover

### ISSUE THREAD

**Issue by wgrand** [corin8823/Popover#77]
1.0.6 seems to break dismiss when touching outside of popover. I had to revert to version 1.0.5

**Comment by paulshapiro** [comment]
@wgrand Hm… I am unable to repro this. Still occurring for you with latest code?
Thanks
Paul

**Comment by wgrand** [comment]
I upgraded back to 1.0.6 and I no longer seem to experience the issue. I might have had something set up differently on my end.
