### ISSUE TITLE
iOS11 not show

### ISSUE THREAD

**Issue by codwam** [corin8823/Popover#82]
open func show(_ contentView: UIView, point: CGPoint) {
//    guard let rootView = UIApplication.shared.windows.last ?? UIApplication.shared.keyWindow else {
//        return
//    }
    // This works good
    guard let rootView = UIApplication.shared.keyWindow ?? UIApplication.shared.windows.last else {
        return
    }
    self.show(contentView, point: point, inView: rootView)
  }

In iOS11:
`UIApplication.shared.keyWindow ?? UIApplication.shared.windows.last` is `_UIInteractiveHighlightEffectWindow `?

**Comment by parbo86** [comment]
I would suggest to take UIWindow from "fromView" parameter in 
`open func show(_ contentView: UIView, fromView: UIView, inView: UIView) {
if let window = fromView.window{
// show popover
}
}`
I experienced an issue when UIKeyboard animation just completed but keyboard window was still  both "key" and "last" window of the UIApplication.

**Comment by codwam** [comment]
The below code repeat 3 times:
`
 guard let rootView = UIApplication.shared.windows.last ?? UIApplication.shared.keyWindow else 
{</br>
 return
 }
`
Make a `constant` or `let` declear it may be better?
And the `fromView` in parameters should have a default value I think.

Close Any Time.

**Comment by vrwim-bazookas** [comment]
Also fixed in #80 @corin8823
