### ISSUE TITLE
Not working/showing in iPhone X

### ISSUE THREAD

**Issue by chonex143** [corin8823/Popover#91]
- iOS 11 is now release with new phone X, 8 and 8+.

On iPhone X the popover is not showing.

**Comment by chonex143** [comment]
I just do [in your PR](https://github.com/corin8823/Popover/pull/85) or [In stockoverflow](https://stackoverflow.com/questions/44379348/the-use-of-swift-3-objc-inference-in-swift-4-mode-is-deprecated) to run the library properly and it works now.

- Hope you fix for the future.

**Comment by chonex143** [comment]
Issue same #88

**Comment by khantthulinn** [comment]
yes. same. will you guys fix soon? if not, I gona need to find another library since our app launch is very near to support ios 11.  Or is there any temp workaround?
