### ISSUE TITLE
IOS 11 FIX

### ISSUE THREAD

**Issue by chonex143** [corin8823/Popover#92]
In your `open func show(_ contentView: UIView, fromView: UIView) {`
please re-make this code. This will only get the `keyWindow` in the main app

```
guard let window = UIApplication.shared.keyWindow else {
        return
    }
self.show(contentView, fromView: fromView, inView: window)
```

Dont use `[window]`.

**Comment by corin8823** [comment]
Thanks issue.

What kind of change do you want?
Please try out the PR.

The current code is below.
https://github.com/corin8823/Popover/blob/master/Classes/Popover.swift#L204

**Comment by chonex143** [comment]
Ok thanks.
